apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: albertatabekyan/spring-boot:kafka-consumer-1
          ports:
            - containerPort: 80
          env:
            - name: BOOTSTRAP_SERVER
              value: kafka-0:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer
  ports:
    - name: kafka-consumer
      port: 80
      targetPort: 8087