server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: secretkey123