apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: albertatabekyan/spring-boot:kafka-producer-1
          ports:
            - containerPort: 80
          env:
            - name: BOOTSTRAP_SERVER
              value: kafka-0:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
spec:
  selector:
    app: kafka-producer
  ports:
    - name: kafka-producer
      port: 80
      targetPort: 8086